SPRING_KAFKA_ENABLED: true
SPRING_KAFKA_BOOTSTRAP_SERVERS: http://localhost:9092
SPRING_KAFKA_TOPIC: SHIPPING_ORDER_EVENTS
SPRING_KAFKA_DISABLED_EVENTS:
SPRING_KAFKA_TOPIC_AUTO_CREATE: true

server:
  port: 8081
  contextPath: /tmf-api/shippingOrder/v4.0/

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org.mongodb.driver: ERROR
    ROOT: INFO

spring:
  data:
    # ======== MongoDB =========
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/shippingOrder?connectTimeoutMS=30000&minPoolSize=0&maxPoolSize=5&authSource=admin
  kafka:
    enabled: ${SPRING_KAFKA_ENABLED}
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS} #url of kafka cluster
    topics:
      shipping-order: ${SPRING_KAFKA_TOPIC}
    disabled-events: ${SPRING_KAFKA_DISABLED_EVENTS}
    topic-auto-create: ${SPRING_KAFKA_TOPIC_AUTO_CREATE}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      enable-auto-commit: false
    listener:
      ack-mode: batch

href:
  address: http://localhost:8081/tmf-api/shippingOrder/v4.0/shippingOrder/

